

module AbsGrammar where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
newtype Error = Error String deriving (Eq, Ord, Show, Read)
data Program = Prog [Stmt]
  deriving (Eq, Ord, Show, Read)

data Boolean = BTrue | BFalse
  deriving (Eq, Ord, Show, Read)

data Map = MapKV Value Value
  deriving (Eq, Ord, Show, Read)

data Literal
    = LInt Integer
    | LBool Boolean
    | LStr String
    | LErr Error
    | LArr [Value]
    | LTup [Value]
    | LMap [Map]
    | LFun
  deriving (Eq, Ord, Show, Read)

data Exp
    = ECall Call
    | EVar Ident
    | EInt Integer
    | ETimes Exp Exp
    | EDiv Exp Exp
    | EMod Exp Exp
    | EPlus Exp Exp
    | EMinus Exp Exp
  deriving (Eq, Ord, Show, Read)

data BExp
    = BCall Call
    | BVar Ident
    | BBool Boolean
    | BLt Exp Exp
    | BGt Exp Exp
    | BLe Exp Exp
    | BGe Exp Exp
    | BEq Exp Exp
    | BNot BExp
    | BAnd BExp BExp
    | BOr BExp BExp
  deriving (Eq, Ord, Show, Read)

data Type
    = TInt
    | TBool
    | TError
    | TString
    | TArray Type
    | TMap Type Type
    | TTuple [Type]
    | TFunc Type Ret
  deriving (Eq, Ord, Show, Read)

data Ret = RVoid | RType Type
  deriving (Eq, Ord, Show, Read)

data Param = PVal Ident Type | PRef Ident Type
  deriving (Eq, Ord, Show, Read)

data Func = FLambda [Param] Ret [Stmt] | FFunc Ident
  deriving (Eq, Ord, Show, Read)

data Call = CFun Ident [Value] | CMet Ident Ident [Value]
  deriving (Eq, Ord, Show, Read)

data Value
    = VLit Literal
    | VVar Ident
    | VFunc Func
    | VCall Func [Value]
    | VExp Exp
    | VBExp BExp
  deriving (Eq, Ord, Show, Read)

data Var = AVar Ident
  deriving (Eq, Ord, Show, Read)

data Decl
    = DVar Ident Type
    | DVarI Ident Type Value
    | DFunc Ident [Param] Ret [Stmt]
  deriving (Eq, Ord, Show, Read)

data Elif = EElif BExp [Stmt]
  deriving (Eq, Ord, Show, Read)

data Else = EElse [Stmt]
  deriving (Eq, Ord, Show, Read)

data Stmt
    = SDecl Decl
    | SAssign [Var] Value
    | SCall Call
    | SIf BExp [Stmt] [Elif]
    | SIfelse BExp [Stmt] [Elif] Else
    | SWhile BExp [Stmt]
    | SFor Ident Integer Integer [Stmt]
    | SReturn Value
    | SDefer Call
    | SPrint Value
  deriving (Eq, Ord, Show, Read)

